// Which image appears where.
//
// Files are generated by `npm run images` from assets/originals/ via the
// manifest in scripts/build-images.mjs. Do not hand-place files in
// public/images/ — they are wiped and rebuilt.
//
// Every derivative is EXACTLY 1400x1400 (lg) and 800x800 (sm). The layout's
// aspect-ratio rules are 1/1 to match, so the browser never crops on top of
// the crop already applied. Change both together or not at all.
const img = slug => ({ lg: `/images/lg/${slug}.jpg`, sm: `/images/sm/${slug}.jpg` })

const IMAGES = {
  hero:        img('bmw-m2-dubshack-motorsport-workshop-stoke-on-trent'),
  servicing:   img('bmw-servicing-repairs-stoke-on-trent'),
  german:      img('audi-rs-specialist-stoke-on-trent'),
  performance: img('performance-exhaust-system-stoke-on-trent'),
  motorsport:  img('bmw-track-race-car-preparation-stoke-on-trent'),
  alignment:   img('bmw-m-wheel-alignment-geometry-stoke-on-trent'),
  workshop:    img('dubshack-motorsport-workshop-longton-stoke-on-trent'),

  // Blurred background bands on the service pages.
  bandServicing:   img('band-servicing-workshop-stoke-on-trent'),
  bandGerman:      img('band-mercedes-amg-stoke-on-trent'),
  bandPerformance: img('band-bmw-m4-performance-stoke-on-trent'),
  bandMotorsport:  img('band-bmw-race-car-stoke-on-trent'),
}

export default IMAGES
